### ISSUE TITLE
超时问题

### ISSUE THREAD

**Issue by dreamshit** [weibocom/motan-php#4]
Connection.php中有个写死的1000000。
可以在ReadMe中说明.
遇到问题从服务端超时到代理超时挨个排查。

**Comment by idevz** [comment]
@dreamshit 感谢指出，也欢迎 PR。

**Comment by dreamshit** [comment]
最近学习下github怎么玩。希望为motan发展出份力。这个贴出来先为帮助遇到同样情况的人快速找到问题点。关闭当前问题
