### ISSUE TITLE
Error to read header_buffer

### ISSUE THREAD

**Issue by GDSGD** [weibocom/motan-php#7]
目前走的motan-go代理访问JAVA服务，
JAVA服务后面会同步对接一个较耗时的服务(1~4秒处理时长)
motan-go配置的6秒超时，如果JAVA服务耗时短则motan-php正常接收返回结果，但是如果耗时长，motan-php这边基本在2秒左右，报Error to read header_buffer异常，
这个异常是什么场景下会报
结合motan-go应该如何配置motan-php的超时时长？

**Comment by GDSGD** [comment]
motan-go的access log日志为:
access log--server:10.100.10.10:7011,pt:4192, req:com.synative.cs.router.api.mapi.ApplyCross,apply,,1525880998123415778, res:4192,true,<nil>
只是耗时长超过4秒。
跟motan-php的2秒即异常跟预期的不一样

**Comment by GDSGD** [comment]
是否和Connection.php中函数：_setStreamOpt中的@stream_set_timeout($this->_connection, 0, $read_time_out * 1000000);这句有关

**Comment by GDSGD** [comment]
哦，找到，在这里，URL里不设置，默认的：const MOTAN_READ_TIME_OUT = 2;

**Comment by idevz** [comment]
：） 是这样的，PHP 的默认读超时是 2 s .
